CONNECT TO PANDA;
CREATE TABLE
    PANDA.TASK_GROUP
    (
        GROUP_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO
        CACHE ) ,
        GROUP_NAME VARCHAR (50) NOT NULL ,
		GROUP_DESCRIPTION VARCHAR (50),
		CREATE_DATE TIMESTAMP ;
        CONSTRAINT CC1427794631211 PRIMARY KEY ( GROUP_ID)
    )
    IN PANDASPACE;
CREATE TABLE
    PANDA.USER_TASK_GROUP
    (
        USER_ID INTEGER NOT NULL ,
        GROUP_ID INTEGER NOT NULL ,
        CONSTRAINT CC1427794913213 FOREIGN KEY (USER_ID) REFERENCES PANDA."USER" (USER_ID) ON
    DELETE
        NO ACTION
    ON
    UPDATE
        NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION ,
        CONSTRAINT CC1427794922084 FOREIGN KEY (GROUP_ID) REFERENCES PANDA.TASK_GROUP (GROUP_ID)
    ON
    DELETE
        NO ACTION
    ON
    UPDATE
        NO ACTION ENFORCED ENABLE QUERY OPTIMIZATION
    )
    IN PANDASPACE ;
CREATE TABLE
    PANDA.GROUP_TASK
    (
        GROUP_ID INTEGER NOT NULL ,
        TASK_ID INTEGER NOT NULL ,
        RELATIVE_TASK_ID INTEGER ,
        TASK_INDEX INTEGER NOT NULL
    )
    IN PANDASPACE ;
CREATE TABLE
    PANDA.TASK
    (
        TASK_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1000, INCREMENT BY 1, NO
        CACHE ) ,
        TASK_NAME VARCHAR (200) NOT NULL ,
        CATALOG_ID INTEGER NOT NULL ,
        CREATE_DATE TIMESTAMP NOT NULL ,
        LAST_MODIFY TIMESTAMP NOT NULL ,
        COMMENTS VARCHAR (500) NOT NULL
    )
    IN PANDASPACE ;
CREATE TABLE
    PANDA.TASK_PARAMETER
    (
        TASK_ID INTEGER NOT NULL ,
        TASK_PARAMETER XML
    )
    IN PANDASPACE ;
CREATE TABLE
    PANDA.TASK_LOG
    (
		LOG_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO
        CACHE ) ,
        USER_ID INTEGER NOT NULL ,
        GROUP_ID INTEGER NOT NULL ,
        TASK_LOG VARCHAR (1000) NOT NULL ,
        EXECUTE_DATE TIMESTAMP NOT NULL,
		TASK_STATUS INTEGER  NOT NULL
    )
    IN PANDASPACE ;
ALTER TABLE PANDA.GROUP_TASK ADD CONSTRAINT CC1428479722867 FOREIGN KEY (GROUP_ID) REFERENCES PANDA.TASK_GROUP (GROUP_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION ;
ALTER TABLE PANDA.GROUP_TASK ADD CONSTRAINT CC1428481118950 FOREIGN KEY (TASK_ID) REFERENCES PANDA.TASK (TASK_ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION ;
ALTER TABLE PANDA.TASK ADD CONSTRAINT CC1428480645986 PRIMARY KEY ( TASK_ID) ;
CONNECT RESET;